version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./application:/application
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php

  php:
    container_name: php
    build: ./services/php
    volumes:
      - ./application:/application
    env_file:
      - .env.api

  worker:
    container_name: worker
    build: ./services/worker
    volumes:
      - ./application:/application
    env_file:
      - .env.api
    working_dir: /application/api
    command: "php artisan queue:work --tries=3"

  node:
    container_name: node
    image: node
    ports:
      - 80:8080
    volumes:
      - ./application:/application
    working_dir: /application/client
    command: ["npm", "run", "dev"]
